sonar.projectKey=MiAppNetCore
sonar.working.directory=C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\herre\\MiAppNetCore
sonar.pullrequest.cache.basepath=C:\\Users\\herre\\MiAppNetCore

EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.projectKey=MiAppNetCore:EDE0D13F-7DEB-C899-B7F3-A102E40DBA77
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.projectName=MiAppNetCore
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.projectBaseDir=C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.sourceEncoding=utf-8
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.tests=
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.sources=\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\Program.cs",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\WeatherService.cs",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\MiAppNetCore.GlobalUsings.g.cs",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\MiAppNetCore.AssemblyInfo.cs",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\MiAppNetCore.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\appsettings.Development.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\appsettings.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\MiAppNetCore.http",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\Properties\\launchSettings.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\MiAppNetCore.csproj.nuget.dgspec.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\project.assets.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\bin\\Debug\\net10.0\\MiAppNetCore.deps.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\bin\\Debug\\net10.0\\MiAppNetCore.runtimeconfig.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\bin\\Debug\\net10.0\\MiAppNetCore.staticwebassets.endpoints.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore\\obj\\Debug\\net10.0\\staticwebassets.build.json"

EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\0"
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\0\\Issues.json"
EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.cs.scanner.telemetry=\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\0\\Telemetry.json"

EDE0D13F-7DEB-C899-B7F3-A102E40DBA77.sonar.working.directory=C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\.sonar\\mod0
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.projectKey=MiAppNetCore:3680B074-B0D6-C483-8C48-03FBF976E1C4
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.projectName=MiAppNetCore.Tests
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.projectBaseDir=C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore.Tests
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.sourceEncoding=utf-8
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.sources=
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.tests=\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore.Tests\\obj\\MiAppNetCore.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore.Tests\\obj\\project.assets.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore.Tests\\bin\\Debug\\net10.0\\MiAppNetCore.Tests.deps.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore.Tests\\bin\\Debug\\net10.0\\MiAppNetCore.Tests.runtimeconfig.json",\
"C:\\Users\\herre\\MiAppNetCore\\MiAppNetCore.Tests\\UnitTest1.cs"

3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\1",\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\2"
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\1\\Issues.json",\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\2\\Issues.json"
3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.cs.scanner.telemetry=\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\1\\Telemetry.json",\
"C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\2\\Telemetry.json"

3680B074-B0D6-C483-8C48-03FBF976E1C4.sonar.working.directory=C:\\Users\\herre\\MiAppNetCore\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/*.trx
sonar.exclusions=**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=EDE0D13F-7DEB-C899-B7F3-A102E40DBA77,3680B074-B0D6-C483-8C48-03FBF976E1C4

